assignment2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sqlapp/', include('sqlapp.urls'), name='sqlapp'),
    path('', views.home_view)
]

sqlapp/urls.py
from django.urls import path
from . import views

app_name = 'sqlapp'

urlpatterns = [
    path('disease_type/', views.disease_type, name='disease_type'),
    path('create_disease_type/', views.create_disease_type, name='create_disease_type'),
    path('edit_disease_type/<int:id>/', views.edit_disease_type, name='edit_disease_type'),
    path('delete_disease_type/<int:id>/', views.delete_disease_type, name='delete_disease_type'),

    path('country/', views.country, name='country'),
    path('disease/', views.disease, name='disease'),
    path('discover/', views.discover, name='discover'),
    path('users/', views.users, name='users'),
    path('public_servant/', views.public_servant, name='public_servant'),
    path('doctor/', views.doctor, name='doctor'),
    path('specialize/', views.specialize, name='specialize'),
    path('record/', views.record, name='record')



]

sqlapp/models.py
from django.db import models
import datetime

# Create your models here.
class DiseaseType(models.Model):
    id=models.IntegerField
    description=models.CharField(max_length=140)
class Country(models.Model):
    cname=models.CharField(max_length=50)
    population=models.BigIntegerField
class Disease(models.Model):
    disease_code=models.CharField(max_length=50)
    pathogen=models.CharField(max_length=100)
    description=models.CharField(max_length=140)
    id=models.ForeignKey(DiseaseType, on_delete=models.CASCADE,primary_key=True)
class Discover(models.Model):
    cname=models.ForeignKey(Country, on_delete=models.CASCADE)
    disease_code = models.ForeignKey(Disease, on_delete=models.CASCADE,primary_key=True)
    first_enc_date = models.DateField(default=datetime.date.today())
class Users(models.Model):
    email=models.CharField(max_length=60)
    name=models.CharField(max_length=30)
    surname=models.CharField(max_length=40)
    salary=models.IntegerField(default=500000)
    phone=models.CharField(max_length=20)
    cname=models.ForeignKey(Country, on_delete=models.CASCADE)
class PublicServant(models.Model):
    email=models.ForeignKey(Users,on_delete=models.CASCADE)
    department=models.CharField(max_length=50)

class Doctor(models.Model):
    email=models.ForeignKey(Users, on_delete=models.CASCADE)
    degree=models.CharField(max_length=20)
class Specialize(models.Model):
    id=models.ForeignKey(DiseaseType, on_delete=models.CASCADE,primary_key=True)
    email=models.ForeignKey(Doctor, on_delete=models.CASCADE)
class Record(models.Model):
    total_death=models.IntegerField(default=200000)
    total_patients=models.IntegerField(default=200000)
    disease_code=models.ForeignKey(Disease,on_delete=models.CASCADE,primary_key=True)
    cname=models.ForeignKey(Country,on_delete=models.CASCADE)
    email=models.ForeignKey(PublicServant,on_delete=models.CASCADE)

assignment2/views.py
from django.shortcuts import render

def home_view(request):
    return render(request,'home.html')

sqlapp/views.py
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render
from .models import *
# Create your views here.
def disease_type(request):
    diseasetype = DiseaseType.objects.all()
    return render(request, "sqlapp/disease_type/disease_type.html", {"diseasetype": diseasetype})
def create_disease_type(request):
    if request.method == "POST":
        diseasetype = DiseaseType()
        diseasetype.id = request.POST.get("ID")
        diseasetype.description = request.POST.get("description")
        diseasetype.save()
    return HttpResponseRedirect("/sqlapp/disease_type/")
def edit_disease_type(request, id):
    try:
        diseasetype = DiseaseType.objects.get(id=id)

        if request.method == "POST":
            diseasetype.id = request.POST.get("ID")
            diseasetype.description = request.POST.get("description")
            diseasetype.save()
            return HttpResponseRedirect("/sqlapp/disease_type/")
        else:
            return render(request, "sqlapp/disease_type/edit_disease_type.html", {"diseasetype": diseasetype})
    except DiseaseType.DoesNotExist:
        return HttpResponseNotFound("<h2>Disease-type not found</h2>")
def delete_disease_type(request, id):
    try:
        diseasetype = DiseaseType.objects.get(id=id)
        diseasetype.delete()
        return HttpResponseRedirect("/sqlapp/disease_type/")
    except DiseaseType.DoesNotExist:
        return HttpResponseNotFound("<h2>Disease-type not found</h2>")

def country(request):
    country = Country.objects.all()
    return render(request, "sqlapp/country/country.html", {"country": country})
def disease(request):
    disease = Disease.objects.all()
    return render(request, "sqlapp/disease/disease.html", {"disease": disease})
def discover(request):
    discover = Discover.objects.all()
    return render(request, "sqlapp/discover/discover.html", {"discover": discover})
def users(request):
    users = Users.objects.all()
    return render(request, "sqlapp/users/users.html", {"users": users})
def public_servant(request):
    pub = PublicServant.objects.all()
    return render(request, "sqlapp/public_servant/public_servant.html", {"pub": pub})
def doctor(request):
    doctor = Doctor.objects.all()
    return render(request, "sqlapp/doctor/doctor.html", {"doctor": doctor})
def specialize(request):
    spec = Specialize.objects.all()
    return render(request, "sqlapp/specialize/specialize.html", {"spec": spec})
def record(request):
    rec = Record.objects.all()
    return render(request, "sqlapp/record/record.html", {"rec": rec})

sqlapp/templates/sqlapp/country/country.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Country</title>
</head>
<body>
<h2>Country</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Country name</label><br>
            <input type="text" name="country_name" />
        </p>
        <p>
            <label>Population</label><br>
            <input type="number" name="population" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if country.count > 0 %}
    <h2>Country List</h2>
    <table>
        <thead><th>Name</th><th>Population</th><th></th></thead>
        {% for i in country %}
        <tr>
            <td>{{ i.cname }}</td>
            <td>{{ i.population }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/discover/discover.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Discovery</title>
</head>
<body>
<h2>Discover</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Country Name</label><br>
            <input type="text" name="disease_code" />
        </p>
        <p>
            <label>Disease Code</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>First Encountered Date</label><br>
            <input type="date" name="population" />

        </p>
        <input type="submit" value="Save" >
    </form>
    {% if discover.count > 0 %}
    <h2>Discovery List</h2>
    <table>
        <thead><th>Country Name</th><th>Disease Code</th><th>First Encountered Date</th><th></th></thead>
        {% for i in discover %}
        <tr>
            <td>{{ i.cname }}</td>
            <td>{{ i.disease_code }}</td>
            <td>{{ i.first_enc_date }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/disease/disease.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Disease</title>
</head>
<body>
<h2>Disease</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Disease Code</label><br>
            <input type="text" name="disease_code" />
        </p>
        <p>
            <label>Pathogen</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>Description</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>Id</label><br>
            <input type="number" name="population" />

        </p>
        <input type="submit" value="Save" >
    </form>
    {% if disease.count > 0 %}
    <h2>Disease List</h2>
    <table>
        <thead><th>Disease Code</th><th>Pathogen</th><th>Description</th><th>Id</th><th></th></thead>
        {% for i in disease %}
        <tr>
            <td>{{ i.disease_code }}</td>
            <td>{{ i.pathogen }}</td>
            <td>{{ i.description }}</td>
            <td>{{ i.id }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/disease_type/disease_type.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Disease Type</title>
</head>
<body>
    <h2>Disease Type</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>ID</label><br>
            <input type="number" name="ID" />
        </p>
        <p>
            <label>Description</label><br>
            <input type="text" name="description" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if diseasetype.count > 0 %}
    <h2>Disease-type List</h2>
    <table>
        <thead><th>Id</th><th>Description</th><th></th></thead>
        {% for i in diseasetype %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.description }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/disease_type/edit_disease_type.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Edit Disease-type</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label>ID</label><br>
            <input type="number" name="ID" value="{{i.id}}" />
        </p>
        <p>
            <label>Description</label><br>
            <input type="text" name="description" value="{{i.description}}" />
        </p>
        <input type="submit" value="Save" >
    </form>
</body>
</html>

sqlapp/templates/sqlapp/doctor/doctor.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Doctor</title>
</head>
<body>
<h2>Doctor</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Email</label><br>
            <input type="text" name="country_name" />
        </p>
        <p>
            <label>Degree</label><br>
            <input type="text" name="population" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if doctor.count > 0 %}
    <h2>Doctor List</h2>
    <table>
        <thead><th>Email</th><th>Degree</th><th></th></thead>
        {% for i in doctor %}
        <tr>
            <td>{{ i.email }}</td>
            <td>{{ i.degree }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/public_servant/public_servant.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Public Servant</title>
</head>
<body>
<h2>Public Servant</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Email</label><br>
            <input type="text" name="country_name" />
        </p>
        <p>
            <label>Department</label><br>
            <input type="text" name="population" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if pub.count > 0 %}
    <h2>Public Servant List</h2>
    <table>
        <thead><th>Email</th><th>Department</th><th></th></thead>
        {% for i in pub %}
        <tr>
            <td>{{ i.email }}</td>
            <td>{{ i.department }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/record/record.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Record</title>
</head>
<body>
<h2>Record</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Total Death</label><br>
            <input type="number" name="disease_code" />
        </p>
        <p>
            <label>Patients</label><br>
            <input type="number" name="population" />

        </p>
        <p>
            <label>Disease Code</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>Country name</label><br>
            <input type="text" name="population" />

        </p>

        <p>
            <label>Email</label><br>
            <input type="text" name="population" />

        </p>
        <input type="submit" value="Save" >
    </form>
    {% if rec.count > 0 %}
    <h2>Record List</h2>
    <table>
        <thead><th>Total Death</th><th>Patients</th><th>Disease Code</th><th>Country Name</th><th>Email</th><th></th></thead>
        {% for i in rec %}
        <tr>
            <td>{{ i.total_death }}</td>
            <td>{{ i.total_patients }}</td>
            <td>{{ i.disease_code }}</td>
            <td>{{ i.cname }}</td>
            <td>{{ i.email }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/specialize/specialize.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Specialize</title>
</head>
<body>
<h2>Specialize</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>ID</label><br>
            <input type="number" name="country_name" />
        </p>
        <p>
            <label>Email</label><br>
            <input type="text" name="population" />
        </p>
        <input type="submit" value="Save" >
    </form>
    {% if spec.count > 0 %}
    <h2>Specialize List</h2>
    <table>
        <thead><th>ID</th><th>Email</th><th></th></thead>
        {% for i in spec %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.email }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

sqlapp/templates/sqlapp/users/users.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Users</title>
</head>
<body>
<h2>Users</h2>
    <form method="POST" action="/sqlapp/create_disease_type/">
        {% csrf_token %}
        <p>
            <label>Email</label><br>
            <input type="text" name="disease_code" />
        </p>
        <p>
            <label>Name</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>Surname</label><br>
            <input type="text" name="population" />

        </p>
        <p>
            <label>Salary</label><br>
            <input type="number" name="population" />

        </p>
        <p>
            <label>Phone</label><br>
            <input type="number" name="population" />

        </p>
        <p>
            <label>Country Name</label><br>
            <input type="number" name="population" />

        </p>
        <input type="submit" value="Save" >
    </form>
    {% if users.count > 0 %}
    <h2>User List</h2>
    <table>
        <thead><th>Email</th><th>Name</th><th>Surname</th><th>Salary</th><th>Phone</th><th>Country Name</th><th></th></thead>
        {% for i in users %}
        <tr>
            <td>{{ i.email }}</td>
            <td>{{ i.name }}</td>
            <td>{{ i.surname }}</td>
            <td>{{ i.salary }}</td>
            <td>{{ i.phone }}</td>
            <td>{{ i.cname }}</td>
            <td><a href="/sqlapp/edit_disease_type/{{i.id}}">Edit</a> | <a href="/sqlapp/delete_disease_type/{{i.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome page</title>
</head>
<style>
    .buttons {
        top: 50%;
        left: 50%;
    }
    .button {
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        background-color: #000000;
    }
</style>
<body>
    <div class = "buttons">

        <a href="{% url 'sqlapp:disease_type' %}">
        <button class="button">
            Disease type
        </button>
        </a>
        <a href="{% url 'sqlapp:country' %}">
        <button class="button">
            Country
        </button></a>
        <a href="{% url 'sqlapp:disease' %}">
        <button class="button">
            Disease
        </button></a>
        <a href="{% url 'sqlapp:discover' %}">
        <button class="button">
            Discover
        </button></a>
        <a href="{% url 'sqlapp:users' %}">
        <button class="button">
            Users
        </button></a>
        <a href="{% url 'sqlapp:public_servant' %}">
        <button class="button">
            Public Servant
        </button></a>
        <a href="{% url 'sqlapp:doctor' %}">
        <button class="button">
            Doctor
        </button></a>
        <a href="{% url 'sqlapp:specialize' %}">
        <button class="button">
            Specialize
        </button></a>
        <a href="{% url 'sqlapp:record' %}">
        <button class="button">
            Record
        </button></a>
    </div>
</body>
</html>